Bring version number current in README
restic/builder pull request #7
Opened 2018-09-23 15:51 UTC by gliptak

2018-09-24 19:59 UTC, fd0 requested changes
Thanks a lot for improving our documentation! Can you please revert the first occurrence of the version? Then we're good to merge this!

2018-09-24 19:59 UTC, fd0 commented on README.md
> +binaries for each restic release starting at 0.9.2.
Hm, that's not correct, can you revert this change?

2018-09-24 20:56 UTC, gliptak commented
updated

2018-09-25 11:06 UTC, fd0 approved these changes
Cool, thanks!

2018-09-25 11:06 UTC, merged